config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  resources :articles
  resources :sites
  mount Sidekiq::Web => "/sidekiq"

  devise_for :users
  # Define your application routes per the DSL in
  # https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :site

  # Adjust the validation to have the intersection of published_on
  validates(
    :slug,
    length: {maximum: 255},
    presence: true,
    uniqueness: {case_sensitive: false}
  )
  validates(:body, presence: true)

  validates(:published_on, presence: true)

  scope :is_published, -> { where(published: true) }
  scope :is_unpublished, -> { where(published: false) }
  scope :is_private, -> { where(public: false) }
  scope :is_public, -> { where(public: true) }
  scope :live, -> { is_public.is_published }

  def body_for_index
    lines = body.split("\n")

    lines[0,3].join("\n")
  end
end

app/models/guest_user.rb
class GuestUser < User
  def admin?
    false
  end

  def logged_in?
    false
  end
end

app/models/site.rb
class Site < ApplicationRecord
  # Add a soft limit on the length of name and URL
  has_many :articles

  validates(
    :name,
    length: {maximum: 250},
    presence: true,
    uniqueness: {case_sensitive: false}
  )
  validates(
    :url,
    length: {maximum: 250},
    presence: true,
    uniqueness: {case_sensitive: false}
  )
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  has_many :articles

  validates :email, presence: true, uniqueness: true
  validates :encrypted_password, presence: true

  def logged_in?
    true
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :update_allowed_parameters, if: :devise_controller?

  def current_user
    super || GuestUser.new
  end

  private

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |user|
      user.permit(:email, :name, :password)
    }

    devise_parameter_sanitizer.permit(:account_update) { |user|
      user.permit(
        :current_password,
        :email,
        :name,
        :password_confirmation,
        :password
      )
    }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(
      :article
    ).permit(
      :body,
      :public,
      :published_on,
      :published,
      :site_id,
      :slug,
      :summary,
      :title,
      :user_id
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_action :set_site, only: %i[show edit update destroy]

  # GET /sites or /sites.json
  def index
    @sites = Site.all
  end

  # GET /sites/1 or /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites or /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to site_url(@site), notice: "Site was successfully created." }
        format.json { render :show, status: :created, location: @site }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1 or /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to site_url(@site), notice: "Site was successfully updated." }
        format.json { render :show, status: :ok, location: @site }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1 or /sites/1.json
  def destroy
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url, notice: "Site was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_site
    @site = Site.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def site_params
    params.require(:site).permit(:name, :url, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  OPTIONS = [
    :autolink,
    :fenced_code_blocks,
    :hard_wrap,
    :highlight,
    :prettify,
    :safe_links_only,
    :underline
  ].freeze

  def markdown(text)
    output = Markdown.new(text, *OPTIONS)

    output.to_html.html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <section id="flashes" data-role="flash-notice">
    <ul>
    <% flash.each do |name, message| -%>
      <li class="flash-<%= name %>"><%= message %></li>
    <% end -%>
    </ul>
  </section>
<% end %>

app/views/application/_footer.html.erb
    <footer>
      <p>&copy;2022 Nathan L. Walls / 7 On The Hill, LLC</p>
      <p><a href="https://github.com/base10/sycamore/">Sycamore is open source software</a>.</p>
    </footer>

app/views/application/_header.html.erb
    <header>
      <h1>Sycamore</h1>

      <section>
      <p>Omnibus headless CMS</p>

      <%= render "user_actions" %>
      </section>
    </header>

app/views/application/_navigation.html.erb
<!-- TODO: Try with devise helper -->
<% if current_user.logged_in? %>
<nav>
  <ul>
    <li><%= link_to("Articles", articles_path) %></li>
    <li><%= link_to("Sites", sites_path) %></li>
    <li><a href="#">Photos</a></li>
    <li><a href="#">Links</a></li>
    <li><a href="#">Topics</a></li>
    <li><a href="#">Tags</a></li>
  </ul>
</nav>
<% end %>

app/views/application/_user_actions.html.erb
<nav id="user_actions">
  <% if current_user.logged_in? %>
    👋 <%= current_user&.name %>
    <%=
      link_to(
        I18n.t("devise.actions.logout"),
        destroy_user_session_path,
        method: :delete,
        data: { turbo_method: "delete" }
      )
    %>
  <% else %>
    <%= I18n.t("home.welcome_visitor") %>

    <%- if controller_name != 'sessions' %>
      <%= link_to I18n.t("devise.actions.login"), new_user_session_path, data: { turbo: false } %>
    <% end %>

    <%- if controller_name != 'registrations' %>
      <%= link_to I18n.t("devise.actions.sign_up"), new_user_registration_path, data: { turbo: false } %>
    <% end %>
  <% end %>
</nav>

app/views/articles/_article.html.erb
<article id="<%= dom_id article %>">
  <h3><%= article.title %></h3>

  <ul class="article-metadata">
    <li><strong>Slug:</strong> <%= article.slug %></li>
    <li><strong>Site:</strong> <%= article.site.name %></li>
    <li><strong>Author:</strong> <%= article.user.name %></li>
    <li><strong>Tags</strong></li>
  </ul>

  <ul class="article-dates">
    <li><strong>Published:</strong> <%= article.published %></li>
    <li><strong>Published on:</strong> <%= article.published_on.strftime("%A, %d %B, %Y") %></li>
    <li><strong>Created at:</strong> <%= article.created_at.strftime("%F %H:%M:%S %z") %></li>
    <li><strong>Updated at:</strong> <%= article.updated_at.strftime("%F %H:%M:%S %z") %></li>
  </ul>

  <section>
    <em><%= markdown(article.summary) %></em>

    <%= markdown(article.body_for_index) %>

    <nav>
      <%= link_to "Show full article", article %>
      <%= link_to "Edit article", edit_article_path(article) %>
    </nav>
  </section>
</article>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :slug, style: "display: block" %>
    <%= form.text_field :slug, required: true, size: 40 %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title, size: 40 %>
  </div>

  <div>
    <%= form.label :summary, style: "display: block" %>
    <%= form.text_area :summary, rows: 4 %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body, rows: 20 %>
  </div>

  <div>
    <%= form.label :site_id, style: "display: block" %>
    <%=
      form.select :site_id,
      Site.all.collect { |site| [site.name, site.id] }, include_blank: false
    %>
  </div>

  <div>
    <%= form.label :published_on, style: "display: block" %>
    <%= form.date_field :published_on %>
  </div>

  <div>
    <%= form.label :published, style: "display: block" %>
    <%= form.check_box :published %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<h1>Articles</h1>

<%= link_to "New article", new_article_path %>

<section id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <hr>
  <% end %>
</section>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<article>
  <h2><%= @article.title %></h2>
  <p><%= @article.published_on.strftime("%A, %d %B, %Y") %>  - enumerate tags</p>

  <ul>
    <li>Created at: <%= @article.created_at.strftime("%F %H:%M:%S %z") %></li>
    <li>Updated at: <%= @article.updated_at.strftime("%F %H:%M:%S %z") %></li>
  </ul>

  <p>By <%= @article.user.name %></p>

  <i><%= markdown(@article.summary) %></i>

  <%= markdown(@article.body) %>

  <nav>
    <%= link_to "Edit this article", edit_article_path(@article) %>
    <%= link_to "Back to articles", articles_path %>

    <%= button_to "Destroy this article", @article, method: :delete %>
  </nav>
</article>

app/views/home/index.html.erb
<section>
  <h2><%= I18n.t("home.header") %></h2>

  <% if current_user.logged_in? %>
    <p>
      Omnibus headless CMS
    </p>
  <% else %>
    <p>
      Devise things here
    </p>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Sycamore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "simple", "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "header" %>
    <%= render "navigation" %>
    <%= render "flashes" -%>

    <%= yield %>

    <%= render "footer" %>
  </body>
</html>

app/views/sites/_form.html.erb
<%= form_with(model: site) do |form| %>
  <% if site.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
        <% site.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :url, style: "display: block" %>
    <%= form.text_field :url %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/sites/_site.html.erb
<tr>
  <td><%= link_to site.name, site %></td>
  <td><%= site.url %></td>

  <td>
    <%= link_to "Edit", edit_site_path(site) %> |
    <%= link_to "Delete", site, method: :delete %>
  </td>
</tr>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render "form", site: @site %>

<br>

<div>
  <%= link_to "Show this site", @site %> |
  <%= link_to "Back to sites", sites_path %>
</div>

app/views/sites/index.html.erb
<h1>Sites</h1>

<table id="sites">
  <tr>
    <th>Name</th>
    <th>URL</th>
    <th></th>
  </tr>
  <% @sites.each do |site| %>
    <%= render site %>
  <% end %>
</table>

<%= link_to "New site", new_site_path %>

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render "form", site: @site %>

<br>

<div>
  <%= link_to "Back to sites", sites_path %>
</div>

app/views/sites/show.html.erb
<div id="<%= dom_id @site %>">
  <p>
    <strong>Name:</strong>
    <%= @site.name %>
  </p>

  <p>
    <strong>URL:</strong>
    <%= @site.url %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @site.description %>
  </p>
</div>

<div>
  <%= link_to "Edit this site", edit_site_path(@site) %> |
  <%= link_to "Back to sites", sites_path %>

  <%= button_to "Destroy this site", @site, method: :delete %>
</div>